# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pinconfform.ui'
#
# Created: Thu Mar 17 17:46:40 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.stackedWidget = QtGui.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 401, 301))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.formLayoutWidget = QtGui.QWidget(self.page)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-1, 10, 401, 222))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.comboBox_3 = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_3)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.LNAddressSpinBox1 = QtGui.QSpinBox(self.formLayoutWidget)
        self.LNAddressSpinBox1.setMinimum(1)
        self.LNAddressSpinBox1.setMaximum(2048)
        self.LNAddressSpinBox1.setObjectName("LNAddressSpinBox1")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.LNAddressSpinBox1)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.ArduinoPinSpinBox1 = QtGui.QSpinBox(self.formLayoutWidget)
        self.ArduinoPinSpinBox1.setMinimum(1)
        self.ArduinoPinSpinBox1.setMaximum(12)
        self.ArduinoPinSpinBox1.setObjectName("ArduinoPinSpinBox1")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ArduinoPinSpinBox1)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.pos1SpinBox = QtGui.QSpinBox(self.formLayoutWidget)
        self.pos1SpinBox.setMinimum(900)
        self.pos1SpinBox.setMaximum(2100)
        self.pos1SpinBox.setProperty("value", 1500)
        self.pos1SpinBox.setObjectName("pos1SpinBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.pos1SpinBox)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_4)
        self.pos2SpinBox = QtGui.QSpinBox(self.formLayoutWidget)
        self.pos2SpinBox.setMinimum(900)
        self.pos2SpinBox.setMaximum(2100)
        self.pos2SpinBox.setProperty("value", 1500)
        self.pos2SpinBox.setObjectName("pos2SpinBox")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.pos2SpinBox)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_5)
        self.speedSpinBox = QtGui.QSpinBox(self.formLayoutWidget)
        self.speedSpinBox.setMinimum(1)
        self.speedSpinBox.setMaximum(255)
        self.speedSpinBox.setSingleStep(10)
        self.speedSpinBox.setObjectName("speedSpinBox")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.speedSpinBox)
        self.pos1Button = QtGui.QPushButton(self.page)
        self.pos1Button.setGeometry(QtCore.QRect(110, 230, 121, 32))
        self.pos1Button.setObjectName("pos1Button")
        self.pos2Button = QtGui.QPushButton(self.page)
        self.pos2Button.setGeometry(QtCore.QRect(230, 230, 113, 32))
        self.pos2Button.setObjectName("pos2Button")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.formLayoutWidget_2 = QtGui.QWidget(self.page_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.ArduinoPinSpinBox2 = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.ArduinoPinSpinBox2.setMinimum(1)
        self.ArduinoPinSpinBox2.setMaximum(12)
        self.ArduinoPinSpinBox2.setObjectName("ArduinoPinSpinBox2")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.ArduinoPinSpinBox2)
        self.ledEffectComboBox = QtGui.QComboBox(self.formLayoutWidget_2)
        self.ledEffectComboBox.setObjectName("ledEffectComboBox")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.ledEffectComboBox)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.LNAddressSpinBox2 = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.LNAddressSpinBox2.setMinimum(1)
        self.LNAddressSpinBox2.setMaximum(2048)
        self.LNAddressSpinBox2.setObjectName("LNAddressSpinBox2")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.LNAddressSpinBox2)
        self.comboBox_2 = QtGui.QComboBox(self.formLayoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_2)
        self.ledValue1pinBox = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.ledValue1pinBox.setObjectName("ledValue1pinBox")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.ledValue1pinBox)
        self.ledValue2SpinBox = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.ledValue2SpinBox.setObjectName("ledValue2SpinBox")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.ledValue2SpinBox)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_12)
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Pin function", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "LocoNet address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Arduino pin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Position 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Position 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.pos1Button.setText(QtGui.QApplication.translate("Form", "Pos 1 (Straight)", None, QtGui.QApplication.UnicodeUTF8))
        self.pos2Button.setText(QtGui.QApplication.translate("Form", "Pos 2 (Thrown)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Arduino Pin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "LED effect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Pin function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "LocoNet address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Effect value 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Effect value 2", None, QtGui.QApplication.UnicodeUTF8))

